<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductosAPI.Models\ProductosAPI.Models.csproj" />
    <ProjectReference Include="..\ProductosAPI.Repositories\ProductosAPI.Repositories.csproj" />
  </ItemGroup>

</Project>
